### ISSUE TITLE
写一份易懂的文档

### ISSUE THREAD

**Issue by simonmysun** [OSOUC/UndergraduateThesisLaTeXTemplate#1]
可以仿照 https://github.com/xueruini/thuthesis

**Comment by zhenghaiyong** [comment]
我基于清华大学的thuthesis直接修改了一个ouc的硕士博士的模板：
https://github.com/zhenglab/thuthesis/tree/ouc
清华模板里面也有本科生的，但我没试，我这边主要是硕士和博士用。

On Sat, May 23, 2015 at 11:05 AM, 孙茂胤 <notifications@github.com> wrote:

> 可以仿照 https://github.com/xueruini/thuthesis
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OSOUC/UndergraduateThesisLaTeXTemplate/issues/1>.
>



-- 
+-------------------------------------------------------------------+
| Haiyong Zheng (郑海永), PhD, Associate Professor
| Department of Electronic Engineering,
| College of Information Science and Engineering,
| Ocean University of China.
| No. 238 Songling Road,
| Qingdao, China 266100
| http://vision.ouc.edu.cn/~zhenghaiyong
+-------------------------------------------------------------------+

**Comment by simonmysun** [comment]
谢谢老师! 我这个是我一个同学和我从零开始写的.. 写的过程还没有借鉴别人的代码, 等答辩了之后好好看看.

**Comment by simonmysun** [comment]
看了一下觉得有点忧伤... 觉得我是改不到这么好了...

**Comment by zhenghaiyong** [comment]
呵呵，没关系。我觉得重在实践，你们能用就很不错了，更何况还想着写个模板。本科生受众太少而且几乎不太会有人用，而且页数也少参考文献图表等都少貌似体现不太出LaTeX的优势（很多人认为学习它不一定值得），但是硕士博士就会“性价比”很高呵呵。
另外，我觉得清华模板在各方面都很完美了（我们学校很多地方没做要求的清华都会有规范，即便都没有的XueRuini也会根据专业做法来规范，毕竟他做了很多年了模板也改版了好几遍），没必要从头写，就在他基础上针对一些细节修改就很完美了呵呵。

发自我的 iPhone

**Comment by simonmysun** [comment]
Done by @Hsmouc .

https://github.com/OSOUC/UndergraduateThesisLaTeXTemplate/commit/0c9353a310a981617a71f00e84ebcf7634252fad
