### ISSUE TITLE
长标题封面换行问题

### ISSUE THREAD

**Issue by BuckyI** [OSOUC/UndergraduateThesisLaTeXTemplate#14]
标题字数较多时封面显示不全, 论文撰写规范中提到, 论文题目最多是25字.
感觉可以把 `cover.sty` 中标题部分的环境由 `centerline` 换成 `center`
![image](https://user-images.githubusercontent.com/44031088/165719672-790bfadb-0a80-4817-b59d-d7339537b866.png)

**Comment by Hsmouc** [comment]
感谢，我最近会抽时间测试一下 :)
