### ISSUE TITLE
跨平台使用：关于在macOS下的字体问题

### ISSUE THREAD

**Issue by Hsmouc** [OSOUC/UndergraduateThesisLaTeXTemplate#3]
我在macOS下使用这份模版完成了毕业论文的排版，遇到了用XeLaTeX编译会出字体错误的问题，需要将Windows下的SimSun字体更换为STSong才可以正常编译。解决方案是在oucart.cls中将如下代码：
```
\setCJKmainfont{SimSun}
\setCJKsansfont{SimHei}
\setCJKmonofont{FangSong}
```
更改为：
```
\setCJKmainfont[BoldFont=STHeiti,ItalicFont=STKaiti]{STSong}
\setCJKsansfont[BoldFont=STHeiti]{STXihei}
\setCJKmonofont{STFangsong}
```
p.s. 感谢学长完成了一份LaTeX毕业论文模版。

**Comment by simonmysun** [comment]
还是要感谢你使用这份模板并及时反馈问题和解决方案。你的感谢我已经转达给它的主要作者。

因为我手头没有 Mac
设备无法测试，不知道你是否可以帮忙改成兼容常见系统的写法或者将华文、中易或者其他系列的这三种字体加入到代码仓库中（如果字体的开元协议允许）？

这份模板是从当时我自己的工作流中整理出来的，现在看来各方面也都不够完善，加上现在毕业已久，已经不知道这份模板是否还符合当下的要求，也不知道如何找到接手这个项目的人。你有没有兴趣继续维护下去呀？或者帮忙联系低年纪的同学来维护？

tel:+49 15256965008 <+49+15256965008>
mailto:simonmysun@gmail.com <simonmysun@gmail.com>
https://simonmysun.github.io
[image: Avatar]He is nothing now.

在 2018年5月19日 上午11:52，Hsmouc <notifications@github.com>写道：

**Comment by Hsmouc** [comment]
我可以将模版维护到符合今年的要求，并保证跨平台的可用性。已联系同专业的同学@lennox67在Linux上测试。
- 关于现在的格式要求：没有找到学校给出正文行距、页边距之类细化的要求，不过我可以按照我所在专业的要求更新模版格式。
- 关于继续维护：我可以接手这个项目，不过我今年也要离开OUC了，我可以尽量联系数院/信院/工院有兴趣的同学继续把这个项目做下去。（我是工院的 逃～
- 关于文档：我可以写一份使用手册。

**Comment by simonmysun** [comment]
多谢了！

学校的要求不会太详细的，会留出一些允许老师打回去修改的空间。模板的二次开发的方便程度也是我们需要追去的目标之一。

如果还有可能，希望能把 GitHub 上的这个组织也延续下去，方便同学们互相认识，共同开发一些有趣的项目。

**Comment by Hsmouc** [comment]
好的
