### ISSUE TITLE
Linux下字体怎么办

### ISSUE THREAD

**Issue by Bugatti100Peagle** [OSOUC/UndergraduateThesisLaTeXTemplate#8]
我部署在服务器上，使用sharelatx，镜像系统为Debian，宿主机系统为Ubuntu18.04，关于字体有没有什么办法？

**Comment by simonmysun** [comment]
你好，感谢你使用这个模板。字体在模板文件中是通过 setCJKmainfont 等指令设置的：

https://github.com/OSOUC/UndergraduateThesisLaTeXTemplate/blob/master/oucart.cls#L15

你可以修改模板中的字体路径到正确位置或者在你的论文源码中覆盖这些设置。

关于字体的选择模板中在 Windows 环境使用的是中易系列字体，在 Mac 环境是华文系列。不建议将这两个系统自带的字体导出自用。可以免费合理使用的字体很多，如[方正书宋](http://www.foundertype.com/index.php/FontInfo/index/id/151.html)、[方正黑体](http://www.foundertype.com/index.php/FontInfo/index/id/131)、[方正仿宋](http://www.foundertype.com/index.php/FontInfo/index/id/128)，或者[思源](https://source.typekit.com/source-han-serif/) / [Noto](https://www.google.com/get/noto/) 系列等。

如果你有兴趣，希望也能将这个项目接手下去，保持模板更新至最新的论文格式要求并使之尽可能方便以后的同学使用。

**Comment by Bugatti100Peagle** [comment]
算了，服务器配置太膈应，还是本地编译吧。正好我在肝毕业论文，非常感谢有这样的模板，目前格式没有太大变化。

**Comment by simonmysun** [comment]
Ok. Closed.
