### ISSUE TITLE
运行到makeover时报错的问题

### ISSUE THREAD

**Issue by J-Danyang** [OSOUC/UndergraduateThesisLaTeXTemplate#9]
编译环境：macOS + TeX Live 2019

问题：按照manual上说的手动编译顺序进行编译的时候，到\makecover ... \includegraphics 的时候就报错了。

我的解决方法：在oucart.cls里面加了\RequirePackage{graphicx}。

我也尝试使用了\RequirePackage{graphics}，但这个宏包会导致“Paragraph ended before \Gin@iii was complete"的错误。

**Comment by simonmysun** [comment]
你好，谢谢你所做的尝试，如果你的解决方案可行请提交 pull request。我手头没有相关环境，如果能有 Windows 和 Linux 环境的测试结果最好了。

**Comment by Hsmouc** [comment]
我在macOS上测试了模版，似乎没有你说的问题。\RequirePackage{graphicx}在Line 28, oucart.cls，我怀疑是release的版本没有跟上代码的更新，现在用release里面下载的模版应该不会再有问题了。
